# Generated by Django 5.1.1 on 2024-10-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
    ]
