# Generated by Django 5.1.1 on 2024-10-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_tag_item_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='popularity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
